#!/bin/bash
mvn clean install
STATUS=$?
if [ $STATUS -eq 0 ]; then
sh /home/yaroslav/usr/glassfish4/bin/asadmin redeploy --name patient-database-web-1.0-SNAPSHOT /home/yaroslav/workspace/patients-test/patient-database-web/target/patient-database-web-1.0-SNAPSHOT.war
fi

